
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import gsap from "gsap";
import { ScrollSmoother, ScrollTrigger } from "gsap/all";
import IconAnimation from "@/components/icon";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-base-01`}
      >
        <header className="p-6 sticky top-0 grid grid-cols-1 font-sans text-2xl mix-blend-difference text-light-white z-10">
          <Link href="/">Clara McNair</Link>
        </header>
        
        
        {children}
        
        <IconAnimation/>

        <footer className="grid grid-cols-6 gap-5 font-mono p-6 mt-[80px] max-sm:grid-cols-2">
          <div>Clara</div>
          <a className="col-start-3" href="/about">about</a>
          <div>contact</div>
          <a href="">LinkedIn</a>
        </footer>
      </body>
    </html>
  );
}
